# Generated by Django 6.0 on 2026-02-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodels',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datamodels',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
